# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Campus
email: nicolejavorsky@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Where student journalists hack higher education
baseurl: "" # the subpath of your site, e.g. /blog
url: "opencampusnews.github.io" # the base hostname & protocol for your site
twitter_username: opencampusnews
github_username:  opencampusnews

# Build settings
markdown: kramdown
